### ISSUE TITLE
Animated QR codes decoding feature?

### ISSUE THREAD

**Issue by Sami32** [tony-xlh/QRTransfer#1]
Hello there!

I like it but we cannot pick an Animated QR codes file to be decoded.
That would be a nice feature add IMHO ;-)
![sequence-danseur](https://github.com/tony-xlh/QRTransfer/assets/18471069/6c4e9021-767b-4ff2-8065-4df240979f90)

I tested it on Android 7.0 (Xiaomi) where it seem that some freezing occur because it become barely responsive after having done a first sending file test.

Best regards,

**Comment by tony-xlh** [comment]
This is not related to this project which uses multiple QR codes to transfer files.

The first frame of the image is not decodable. But the other frames can be decoded.

![image](https://github.com/tony-xlh/QRTransfer/assets/112376616/e766008a-661f-44cf-8b24-c73a318c2f37)

You can try this demo: https://demo.dynamsoft.com/barcode-reader-js/common-oned-twod/

**Comment by Sami32** [comment]
Thanks for the tips +1
I tried without success even editing this GIF image and remove the first and last frames before uploading it :-(

How did you do to make this animated QR code recognized?

Edit:
I tried with the same frame as you and it worked.
It is far from an streamless process...
